### PR TITLE
Colors modified for lines on AS graph 

### PR DESCRIPTION
**Pull request by zelima**
Modified colors for lines when AS is selected inside the graphs

#7EFFF0
#00D49A
#00BAB5
#5472DE
#6003D4

### CODE REVIEW

**Comment by shiweiart** [comment]
The colours are for the stacked bars, the graphs on the right hand side of the country page. The graphs you guys just design on this sprint!

**Comment by zelima** [comment]
Closing as this should be done for **stacked bar chart** not for AS line graphs

**Comment by shiweiart** [comment]
Here are the colours in the order!
#7EFFF0
#00D49A
#00BAB5
#5472DE
#6003D4
#c80210

**Comment by shiweiart** [comment]
Again new ones: let me know if it looks any better
#0765f0
# d3e4fc
#39e7fa
#a9f4fc
# c8b1f9
#793cf5

**Pull request closed without merging**
